insert into CUSTOMER(EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,PHNO)VALUES('Sandeep@1','Dabbakuti','Sandeep','143',1234456789);
insert into CUSTOMER(EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,PHNO)VALUES('madhumathi@1','Dabbakuti','madhu','143',1234456789);
insert into CUSTOMER(EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,PHNO)VALUES('Mounika@1','Dabbakuti','Mounika','143',1234456789);
insert into CUSTOMER(EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,PHNO)VALUES('Swetha@1','Dabbakuti','Swetha','143',1234456789);
insert into EVENT(LOCATION,BOKKED_MOVIE) VALUES('warrior','weimar');
insert into EVENT(LOCATION,BOKKED_MOVIE) VALUES('ThankYou','hof');
insert into EVENT(LOCATION,BOKKED_MOVIE) VALUES('StarWars','Jena');
insert into EVENT(LOCATION,BOKKED_MOVIE) VALUES('JhonWick','Erfurt');